apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-db-pvc
  namespace: spin-the-wheel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn
